# Project Telos Third-Wave Closed-Loop Demo

Date: 2026-07-02

Purpose: move from tool-by-tool claims to one compact proof loop: BuildLang emits a policy-pinned compiler receipt, Learn turns that proof packet into a re-verifiable lesson, Build Color supplies a visible measurement lane, and Telos/Crucible preserve the public handoff boundary.

## Verified Loop

| Segment | Evidence | Boundary |
| --- | --- | --- |
| BuildLang policy receipt | `buildlang-hello-ci-review-receipt.json` was generated by `buildc check examples\quickstart\hello.bld --profile ci-review --expect-profile-digest 265584dc495e50171aaa14ab84e0522a34de5b645a703b360c8209068b36f43b --receipt <path>`. `buildc receipt verify <receipt> --source examples\quickstart\hello.bld --expect-profile ci-review --json` returned `status: passed` with 18 passed checks. | Source-checkout demo only. Does not prove full compiler correctness, language replacement, or Build Universe compilation. |
| Proof packet | `buildlang-hello-proof-packet.json` binds only the source file ref/hash and BuildLang receipt ref/hash. | Packet contains refs and hashes, not source bodies. |
| Learn prooflesson | `node C:\dev\public\learn\src\cli.mjs tutor prooflesson buildlang-hello --packet <packet>` wrote `tutor\buildlang-hello.prooflesson.json`; `learn tutor reverify buildlang-hello` returned `VERIFIED`. | Lesson is a study scaffold and retrieval prompt, not an answer dump or credential bypass. |
| Build Color measurement lane | `python -m build_color.cli --version` reports `Build Color v1.0.2`; `info`, `convert`, and `difference` commands produced numeric outputs; `python -m pytest tests -q` passed 458 tests. | Software-side measurement only. No physical meter, display mutation, ICC install, LUT write, or calibration accuracy claim. |
| Telos measurement bridge | `node demo\measurement-layers.mjs --summary` reports 10 layers and 10 measurements with `MATCH`; `node demo\display-calibration.mjs --summary` reports read-only hardware, 3 targets, 4 patch sets, and 5 artifact types; the two focused tests pass. | Read-only proof contract. Hardware mutation remains disabled. |

## Artifact Map

| Artifact | Role |
| --- | --- |
| `docs/outreach/receipts/third-wave/buildlang-hello-ci-review-receipt.json` | BuildLang check receipt under `ci-review`. |
| `docs/outreach/receipts/third-wave/buildlang-hello-proof-packet.json` | Telos-style proof packet consumed by Learn. |
| `docs/outreach/receipts/third-wave/tutor/buildlang-hello.prooflesson.json` | Learn prooflesson receipt with hash-chain entries. |
| `docs/outreach/receipts/third-wave/build-color-cli-measurement.json` | Build Color CLI and test measurement record. |
| `docs/outreach/receipts/third-wave-tooling-thesis-2026-07-02.json` | Crucible thesis for this pass. |
| `docs/outreach/receipts/third-wave-tooling-measurements-2026-07-02.json` | Measurement rows for the thesis. |

## Re-run Commands

From `C:\dev\public\pubscan\quantalang`:

```powershell
& C:\Users\Zain\AppData\Local\Temp\buildlang-codex-target-20260702\debug\buildc.exe check examples\quickstart\hello.bld --profile ci-review --expect-profile-digest 265584dc495e50171aaa14ab84e0522a34de5b645a703b360c8209068b36f43b --receipt C:\dev\public\telos\docs\outreach\receipts\third-wave\buildlang-hello-ci-review-receipt.json
& C:\Users\Zain\AppData\Local\Temp\buildlang-codex-target-20260702\debug\buildc.exe receipt verify C:\dev\public\telos\docs\outreach\receipts\third-wave\buildlang-hello-ci-review-receipt.json --source examples\quickstart\hello.bld --expect-profile ci-review --json
```

From `C:\dev\public\telos\docs\outreach\receipts\third-wave`:

```powershell
node C:\dev\public\learn\src\cli.mjs tutor prooflesson buildlang-hello --packet C:\dev\public\telos\docs\outreach\receipts\third-wave\buildlang-hello-proof-packet.json
node C:\dev\public\learn\src\cli.mjs tutor reverify buildlang-hello
```

From `C:\dev\public\build-color`:

```powershell
python -m build_color.cli --version
python -m build_color.cli info ff6030
python -m build_color.cli convert ff6030 --to oklab
python -m build_color.cli difference ff6030 ff7040 --metric all
python -m pytest tests -q
```

From `C:\dev\public\telos`:

```powershell
node demo\measurement-layers.mjs --summary
node demo\display-calibration.mjs --summary
node --test demo\measurement-layers.test.mjs demo\display-calibration.test.mjs
crucible run docs\outreach\receipts\third-wave-tooling-thesis-2026-07-02.json --measurements docs\outreach\receipts\third-wave-tooling-measurements-2026-07-02.json --out docs\outreach\receipts\third-wave-tooling-run-2026-07-02.json --report docs\outreach\receipts\third-wave-tooling-report-2026-07-02.md --json
```

If the Crucible output files already exist, use a fresh output/report path. Crucible does not silently overwrite generated reports.

## Public Post Angle

> This is the Telos pattern: a compiler receipt becomes a proof packet; the proof packet becomes a learning object; the learning object re-verifies; a visual measurement lane carries numeric evidence; every claim stays bounded by what was actually checked.

## Do Not Post

- "BuildLang replaces Julia today."
- "BuildLang has fully sound linear types."
- "Learn teaches the answer or completes credentials."
- "Build Color calibrated a physical display."
- "Telos proves new physics from this demo."
- "The PATH installs for Learn, BuildLang, or Emet are fixed."
