# crucible report: Dogfood Pass 0021 Quantum Environment Plan and OpenTelemetry Bridge

## Summary

- thesis_id: `127dabb2fa813b84`
- thesis_seal: `127dabb2fa813b84d567c3a9122d1fa50c2c353d9091544f34483604034adcbf`
- assessment_seal: `945f52a7b1f92006eae10eaa21a1eddf0698d8f8227c285938747a13ead2233d`
- counts: MATCH 11 / DRIFT 0 / UNVERIFIABLE 0
- integrity: seals_ok=True, thesis_ok=True, verdicts_rederive=True

## Verdicts

| Claim | Status | Disposition | Margin | Method | Grounds |
| --- | --- | --- | ---: | --- | --- |
| Pass 0021 created a QuantumFrameworkEnvironmentPlanSet/v1 artifact with status ENVIRONMENT_PLAN_AND_OTEL_BRIDGE_MATCH, 11 package plans, nine negative fixtures, 15 source anchors, OTel status API_IMPORT_MATCH_NONRECORDING, and seal 1ce3a1aaab7392d4a825564415a76e71a4f8b59c2a954dbb794d4ffe7e67cb1f. | MATCH | fenced | 1 | quantum-environment-plan-artifact-review | deviation 0 within tolerance 0.5 |
| Pass 0021 local environment receipt records Python 3.12.10, pip 26.1.2, platform Windows-11-10.0.26220-SP0, and installer boundary PLAN_ONLY_NO_PACKAGE_INSTALL. | MATCH | fenced | 1 | local-environment-review | deviation 0 within tolerance 0.5 |
| Every pass 0021 package plan has QuantumFrameworkPackagePlan/v1 schema, install_now=false, pin_policy RESOLVE_IN_ISOLATED_ENV_THEN_FREEZE_WITH_HASHES, no cloud credentials required for import fixtures, at least one HTTPS source anchor, import targets, a first fixture contract, and a plan hash. | MATCH | fenced | 1 | package-plan-contract-review | deviation 0 within tolerance 0.5 |
| Pass 0021 package plans include qiskit, qiskit-ibm-runtime, amazon-braket-sdk, cirq, pennylane, pyqir, pytket, pytket-qir, cudaq, opentelemetry-api, and opentelemetry-sdk. | MATCH | fenced | 1 | package-plan-membership-review | deviation 0 within tolerance 0.5 |
| Pass 0021 promotion gates include isolated environment, resolve/freeze with hashes, no cloud credentials for framework-import fixtures, no provider execution without live-provider receipts, SDK import is not provider execution, and OTel API non-recording span is not exported trace evidence. | MATCH | fenced | 1 | promotion-gate-review | deviation 0 within tolerance 0.5 |
| Pass 0021 imports opentelemetry-api version 1.41.0, creates a NonRecordingSpan, records is_recording=false, zero trace id, zero span id, and attribute recording status NOT_RECORDED_WITH_API_ONLY_NONRECORDING_SPAN. | MATCH | fenced | 1 | otel-action-bridge-fixture-review | deviation 0 within tolerance 0.5 |
| Pass 0021 QuantumProofDemoContract/v1 includes source anchor, framework import, canonical result, negative fixture, OTel action bridge, and Crucible verdict packet layers. | MATCH | fenced | 1 | quantum-proof-demo-contract-review | deviation 0 within tolerance 0.5 |
| Pass 0021 negative fixtures reject shared-base installation, unpinned runtime demo, credential-required import fixture, SDK import as provider execution, nonrecording OTel span as exported trace, CUDA-Q import as GPU acceleration, QIR without record map, BuildLang runtime without compiler receipt, and color runtime without measurement receipt. | MATCH | fenced | 1 | negative-fixture-review | deviation 0 within tolerance 0.5 |
| Pass 0021 validator reports MATCH with one matched check and zero drift. | MATCH | fenced | 1 | validator-run-review | deviation 0 within tolerance 0.5 |
| Pass 0021 records tool receipts showing Index, Gather, Telos, Forum status/verify, and Crucible status as MATCH while preserving Forum submit as UNVERIFIABLE due to executor JSON parsing. | MATCH | fenced | 1 | tool-receipt-review | deviation 0 within tolerance 0.5 |
| Pass 0021 promotes zero quantum SDK installations, unavailable quantum framework imports, cloud credentials, provider jobs, quantum hardware results, natural laws, or scientific discoveries. | MATCH | fenced | 1 | non-promotion-review | deviation 0 within tolerance 0.5 |

## Measurement Evidence

| Claim | Method | Evidence |
| --- | --- | --- |
| Pass 0021 created a QuantumFrameworkEnvironmentPlanSet/v1 artifact with status ENVIRONMENT_PLAN_AND_OTEL_BRIDGE_MATCH, 11 package plans, nine negative fixtures, 15 source anchors, OTel status API_IMPORT_MATCH_NONRECORDING, and seal 1ce3a1aaab7392d4a825564415a76e71a4f8b59c2a954dbb794d4ffe7e67cb1f. | quantum-environment-plan-artifact-review | schemas/quantum-environment-plan-otel-bridge-pass-0021.json schema=QuantumFrameworkEnvironmentPlanSet/v1; status=ENVIRONMENT_PLAN_AND_OTEL_BRIDGE_MATCH; package_plan_count=11; negative_fixture_count=9; source_anchor_count=15; opentelemetry_action_bridge_fixture status=API_IMPORT_MATCH_NONRECORDING; seal=1ce3a1aaab7392d4a825564415a76e71a4f8b59c2a954dbb794d4ffe7e67cb1f |
| Pass 0021 local environment receipt records Python 3.12.10, pip 26.1.2, platform Windows-11-10.0.26220-SP0, and installer boundary PLAN_ONLY_NO_PACKAGE_INSTALL. | local-environment-review | local_environment schema=LocalPythonEnvironmentReceipt/v1; python_version=3.12.10; pip_version=26.1.2; platform=Windows-11-10.0.26220-SP0; installer_boundary=PLAN_ONLY_NO_PACKAGE_INSTALL |
| Every pass 0021 package plan has QuantumFrameworkPackagePlan/v1 schema, install_now=false, pin_policy RESOLVE_IN_ISOLATED_ENV_THEN_FREEZE_WITH_HASHES, no cloud credentials required for import fixtures, at least one HTTPS source anchor, import targets, a first fixture contract, and a plan hash. | package-plan-contract-review | validator checks QuantumFrameworkPackagePlan/v1 schema; validator checks install_now=false; validator checks pin_policy=RESOLVE_IN_ISOLATED_ENV_THEN_FREEZE_WITH_HASHES; validator checks cloud_credentials_required_for_import_fixture=false; validator checks all source anchors are HTTPS; validator checks import_targets, first_framework_import_fixture, and plan_hash |
| Pass 0021 package plans include qiskit, qiskit-ibm-runtime, amazon-braket-sdk, cirq, pennylane, pyqir, pytket, pytket-qir, cudaq, opentelemetry-api, and opentelemetry-sdk. | package-plan-membership-review | required package plan qiskit present; required package plan qiskit-ibm-runtime present; required package plan amazon-braket-sdk present; required package plan cirq present; required package plan pennylane present; required package plan pyqir present; required package plan pytket present; required package plan pytket-qir present; required package plan cudaq present; required package plan opentelemetry-api present; required package plan opentelemetry-sdk present |
| Pass 0021 promotion gates include isolated environment, resolve/freeze with hashes, no cloud credentials for framework-import fixtures, no provider execution without live-provider receipts, SDK import is not provider execution, and OTel API non-recording span is not exported trace evidence. | promotion-gate-review | ISOLATED_ENVIRONMENT_REQUIRED present; RESOLVE_AND_FREEZE_WITH_HASHES_REQUIRED present; NO_CLOUD_CREDENTIALS_FOR_FRAMEWORK_IMPORT_FIXTURES present; NO_CLOUD_PROVIDER_EXECUTION_WITHOUT_LIVE_PROVIDER_RECEIPT present; SDK_IMPORT_DOES_NOT_PROVE_PROVIDER_EXECUTION present; OTEL_API_NONRECORDING_SPAN_DOES_NOT_PROVE_EXPORTED_TRACE present |
| Pass 0021 imports opentelemetry-api version 1.41.0, creates a NonRecordingSpan, records is_recording=false, zero trace id, zero span id, and attribute recording status NOT_RECORDED_WITH_API_ONLY_NONRECORDING_SPAN. | otel-action-bridge-fixture-review | opentelemetry_action_bridge_fixture distribution=opentelemetry-api; module_imported=true; api_version=1.41.0; span_class=NonRecordingSpan; is_recording=false; trace_id_hex=00000000000000000000000000000000; span_id_hex=0000000000000000; attribute_recording_status=NOT_RECORDED_WITH_API_ONLY_NONRECORDING_SPAN |
| Pass 0021 QuantumProofDemoContract/v1 includes source anchor, framework import, canonical result, negative fixture, OTel action bridge, and Crucible verdict packet layers. | quantum-proof-demo-contract-review | quantum_proof_demo_contract schema=QuantumProofDemoContract/v1; packet_layers include source_anchor_receipts; packet_layers include framework_import_receipt; packet_layers include canonical_result_receipt; packet_layers include negative_fixture_receipts; packet_layers include otel_action_bridge_receipt; packet_layers include crucible_verdict_receipt |
| Pass 0021 negative fixtures reject shared-base installation, unpinned runtime demo, credential-required import fixture, SDK import as provider execution, nonrecording OTel span as exported trace, CUDA-Q import as GPU acceleration, QIR without record map, BuildLang runtime without compiler receipt, and color runtime without measurement receipt. | negative-fixture-review | negative-installing-into-shared-base-env expected_validator_status=REJECT; negative-unpinned-runtime-demo expected_validator_status=REJECT; negative-cloud-credential-required-for-import-fixture expected_validator_status=REJECT; negative-sdk-import-claimed-as-provider-execution expected_validator_status=REJECT; negative-nonrecording-otel-span-claimed-as-exported-trace expected_validator_status=REJECT; negative-cudaq-import-claimed-as-gpu-acceleration expected_validator_status=REJECT; negative-qir-without-record-map expected_validator_status=REJECT; negative-buildlang-runtime-without-compiler-receipt expected_validator_status=REJECT; negative-color-runtime-without-measurement-receipt expected_validator_status=REJECT |
| Pass 0021 validator reports MATCH with one matched check and zero drift. | validator-run-review | schemas/pass-0021-quantum-environment-plan-validator-result.json status=MATCH; match=1; drift=0; checks include QuantumFrameworkEnvironmentPlanSet status MATCH |
| Pass 0021 records tool receipts showing Index, Gather, Telos, Forum status/verify, and Crucible status as MATCH while preserving Forum submit as UNVERIFIABLE due to executor JSON parsing. | tool-receipt-review | schemas/tool-receipts-pass-0021.json status=MATCH_WITH_FORUM_SUBMIT_GAP; index status MATCH; gather status MATCH; gather docs verified=true; telos operator_doctor status MATCH; forum status MATCH entries=13; forum verify chain=true deep=true; forum submit status=UNVERIFIABLE; crucible status MATCH |
| Pass 0021 promotes zero quantum SDK installations, unavailable quantum framework imports, cloud credentials, provider jobs, quantum hardware results, natural laws, or scientific discoveries. | non-promotion-review | schemas/quantum-environment-plan-otel-bridge-pass-0021.json non_promotion_statement states no quantum SDK installs, unavailable quantum framework imports, credentials, provider jobs, hardware, or scientific results; packets/031-quantum-environment-plan-otel-bridge.md states no quantum SDKs were installed and no unavailable quantum framework was imported; schemas/tool-receipts-pass-0021.json non_promotion_statement states no package installation, quantum framework import, recording OTel export, cloud provider execution, or scientific discovery; Current promoted natural laws: none |
