# crucible report: Dogfood Pass 0017 Cloud Quantum Metadata Parser Hardening

## Summary

- thesis_id: `76cc95d75900dfd1`
- thesis_seal: `76cc95d75900dfd1cdcb1791245d943cd2c3a4531fda25b6ed0a6793c517703a`
- assessment_seal: `16bde39313bb3bff66bcb3c1b30ad9b0309bc6d958e7af5e715dc2e43901e8fb`
- counts: MATCH 11 / DRIFT 0 / UNVERIFIABLE 0
- integrity: seals_ok=True, thesis_ok=True, verdicts_rederive=True

## Verdicts

| Claim | Status | Disposition | Margin | Method | Grounds |
| --- | --- | --- | ---: | --- | --- |
| Pass 0017 created a CloudQuantumProviderMetadataParserSet/v1 artifact with status PARSER_PROFILE_MATCH, three parser profiles, eight negative fixtures, seven source anchors, and seal e098df09eb2556049e1b9e676b0ace8f0000d1f0bda7565628e2195711e84b21. | MATCH | fenced | 1 | parser-set-review | deviation 0 within tolerance 0.5 |
| Pass 0017 defines provider metadata parser profiles for Amazon Braket GetDevice, IBM BackendProperties, and Azure Quantum target list/show. | MATCH | fenced | 1 | parser-profile-review | deviation 0 within tolerance 0.5 |
| The Braket parser profile requires device ARN, device type, status, capabilities, payload hash, and rejects simulator or unavailable device-capability hardware claims. | MATCH | fenced | 1 | braket-parser-review | deviation 0 within tolerance 0.5 |
| The IBM parser profile requires backend name, backend version, last update date, qubits, gates, payload hash, and rejects missing calibration or paired simulator-status evidence for hardware claims. | MATCH | fenced | 1 | ibm-parser-review | deviation 0 within tolerance 0.5 |
| The Azure parser profile requires workspace, provider id, target id, target profile, payload hash, and rejects simulator or unverified target-kind hardware claims. | MATCH | fenced | 1 | azure-parser-review | deviation 0 within tolerance 0.5 |
| Pass 0017 defines QuantumRegisterLayoutReceipt/v1 with a Qiskit-style two-qubit measurement map, explicit leftmost/rightmost string positions, and layout hash 04cd4fff62e90a8888e74243fab8bf249d74c795650649c1a545e375fdde49fe. | MATCH | fenced | 1 | register-layout-review | deviation 0 within tolerance 0.5 |
| Pass 0017 defines QuantumPostProcessingReceipt/v1 baseline with raw and normalized result hashes required and mitigation, filtering, and truncation set to false. | MATCH | fenced | 1 | post-processing-review | deviation 0 within tolerance 0.5 |
| Pass 0017 negative fixtures reject missing metadata payload hash, unknown target kind as hardware, omitted register layout, absent endian convention, duplicate JSON keys, binary-as-JSON parsing, missing float precision policy, and post-processing without receipt. | MATCH | fenced | 1 | negative-fixture-review | deviation 0 within tolerance 0.5 |
| Pass 0017 validator reports MATCH with one matched check and zero drift. | MATCH | fenced | 1 | validator-run-review | deviation 0 within tolerance 0.5 |
| Pass 0017 records tool receipts showing Index, Gather, Telos, Forum, and Crucible status MATCH while preserving Forum submit as UNVERIFIABLE due to executor JSON parsing. | MATCH | fenced | 1 | tool-receipt-review | deviation 0 within tolerance 0.5 |
| Pass 0017 promotes zero live provider metadata retrievals, quantum hardware results, quantum advantage claims, theorem proofs, natural laws, or scientific discoveries. | MATCH | fenced | 1 | non-promotion-review | deviation 0 within tolerance 0.5 |

## Measurement Evidence

| Claim | Method | Evidence |
| --- | --- | --- |
| Pass 0017 created a CloudQuantumProviderMetadataParserSet/v1 artifact with status PARSER_PROFILE_MATCH, three parser profiles, eight negative fixtures, seven source anchors, and seal e098df09eb2556049e1b9e676b0ace8f0000d1f0bda7565628e2195711e84b21. | parser-set-review | schemas/cloud-quantum-metadata-parsers-pass-0017.json schema=CloudQuantumProviderMetadataParserSet/v1; status=PARSER_PROFILE_MATCH; parser_profile_count=3; negative_fixture_count=8; source_anchor_count=7; seal=e098df09eb2556049e1b9e676b0ace8f0000d1f0bda7565628e2195711e84b21 |
| Pass 0017 defines provider metadata parser profiles for Amazon Braket GetDevice, IBM BackendProperties, and Azure Quantum target list/show. | parser-profile-review | profile parser-braket-get-device present; profile parser-ibm-backend-properties present; profile parser-azure-target-list present |
| The Braket parser profile requires device ARN, device type, status, capabilities, payload hash, and rejects simulator or unavailable device-capability hardware claims. | braket-parser-review | Braket required_raw_fields include deviceArn; Braket required_raw_fields include deviceType; Braket required_raw_fields include deviceStatus; Braket required_raw_fields include deviceCapabilities; Braket required_raw_fields include payload_hash; Braket rejection rules include simulator and unavailable capabilities |
| The IBM parser profile requires backend name, backend version, last update date, qubits, gates, payload hash, and rejects missing calibration or paired simulator-status evidence for hardware claims. | ibm-parser-review | IBM required_raw_fields include backend_name; IBM required_raw_fields include backend_version; IBM required_raw_fields include last_update_date; IBM required_raw_fields include qubits; IBM required_raw_fields include gates; IBM required_raw_fields include payload_hash; IBM rejection rules include missing qubits/gates and paired simulator-status evidence |
| The Azure parser profile requires workspace, provider id, target id, target profile, payload hash, and rejects simulator or unverified target-kind hardware claims. | azure-parser-review | Azure required_raw_fields include workspace_ref; Azure required_raw_fields include provider_id; Azure required_raw_fields include target_id; Azure required_raw_fields include target_profile; Azure required_raw_fields include payload_hash; Azure rejection rules include simulator target and unverified target kind |
| Pass 0017 defines QuantumRegisterLayoutReceipt/v1 with a Qiskit-style two-qubit measurement map, explicit leftmost/rightmost string positions, and layout hash 04cd4fff62e90a8888e74243fab8bf249d74c795650649c1a545e375fdde49fe. | register-layout-review | register_layout_receipt schema=QuantumRegisterLayoutReceipt/v1; measurement_map includes q[0] to c[0] rightmost; measurement_map includes q[1] to c[1] leftmost; interpretation includes bitstring_10 and bitstring_01; layout_hash=04cd4fff62e90a8888e74243fab8bf249d74c795650649c1a545e375fdde49fe |
| Pass 0017 defines QuantumPostProcessingReceipt/v1 baseline with raw and normalized result hashes required and mitigation, filtering, and truncation set to false. | post-processing-review | post_processing_receipt schema=QuantumPostProcessingReceipt/v1; raw_result_hash_required=true; normalized_result_hash_required=true; mitigation_applied=false; filtering_applied=false; truncation_applied=false |
| Pass 0017 negative fixtures reject missing metadata payload hash, unknown target kind as hardware, omitted register layout, absent endian convention, duplicate JSON keys, binary-as-JSON parsing, missing float precision policy, and post-processing without receipt. | negative-fixture-review | negative-provider-metadata-without-payload-hash expected_validator_status=REJECT; negative-azure-unknown-target-kind-promoted-to-hardware expected_validator_status=REJECT; negative-register-layout-omitted expected_validator_status=REJECT; negative-endian-convention-absent expected_validator_status=REJECT; negative-duplicate-json-key-payload expected_validator_status=REJECT; negative-binary-payload-treated-as-json expected_validator_status=REJECT; negative-float-precision-policy-absent expected_validator_status=REJECT; negative-post-processing-without-receipt expected_validator_status=REJECT |
| Pass 0017 validator reports MATCH with one matched check and zero drift. | validator-run-review | schemas/pass-0017-metadata-parser-validator-result.json status=MATCH; match=1; drift=0; checks include CloudQuantumProviderMetadataParserSet status MATCH |
| Pass 0017 records tool receipts showing Index, Gather, Telos, Forum, and Crucible status MATCH while preserving Forum submit as UNVERIFIABLE due to executor JSON parsing. | tool-receipt-review | schemas/tool-receipts-pass-0017.json status=MATCH_WITH_FORUM_SUBMIT_GAP; tool receipts include index status MATCH; tool receipts include gather status MATCH; tool receipts include telos operator_doctor status MATCH; tool receipts include forum status MATCH and verify MATCH; tool receipts include forum_submit status UNVERIFIABLE; tool receipts include crucible status MATCH; Forum submit error recorded: configured executor did not return valid JSON |
| Pass 0017 promotes zero live provider metadata retrievals, quantum hardware results, quantum advantage claims, theorem proofs, natural laws, or scientific discoveries. | non-promotion-review | packets/027-cloud-quantum-metadata-parser-hardening.md states this is a profile pass; schemas/cloud-quantum-metadata-parsers-pass-0017.json non_promotion_statement states no live provider metadata fetch or cloud job was run; adversarial/pass-0017-metadata-parser-steelman.md recommends non-promotional status; Current promoted natural laws: none |
