import { assertCandidate, assertPacket, OSS_PACKET_SCHEMA } from "./schema.mjs";

export function buildReadinessPacket({ candidate, evidence, now = new Date() }) {
  assertCandidate(candidate);
  const safeEvidence = evidence || {};
  const blockers = blockersForEvidence(safeEvidence);
  const prReady = blockers.length === 0;
  const packet = {
    schema: OSS_PACKET_SCHEMA,
    captured_at: now.toISOString(),
    candidate: {
      repository: candidate.repository.full_name,
      issue: candidate.issue.number,
      issue_url: candidate.issue.url,
      candidate_schema: candidate.schema
    },
    evidence: safeEvidence,
    verdict: safeEvidence.crucible?.verdict || "UNVERIFIABLE",
    blockers,
    pr_ready: prReady,
    operator_next_action: prReady ? "open-pr" : "revise",
    public_pr_draft: prReady ? prDraft(candidate, safeEvidence) : null
  };
  assertPacket(packet);
  return packet;
}

export function isPrReady(packet) {
  assertPacket(packet);
  return packet.pr_ready === true && packet.operator_next_action === "open-pr";
}

function blockersForEvidence(evidence = {}) {
  const blockers = [];
  if (!evidence.reproduction?.command) {
    blockers.push("missing reproduction command");
  }
  if (!Array.isArray(evidence.tests) || !evidence.tests.some((test) => test.status === "passed")) {
    blockers.push("missing passing test evidence");
  }
  if (evidence.crucible?.verdict !== "MATCH") {
    blockers.push("crucible verdict is not MATCH");
  }
  if (!evidence.patch?.summary) {
    blockers.push("missing patch summary");
  }
  return blockers;
}

function prDraft(candidate, evidence) {
  return {
    title: `Fix ${candidate.repository.full_name}#${candidate.issue.number}: ${candidate.issue.title}`,
    body: [
      "## Summary",
      evidence.patch.summary,
      "",
      "## Evidence",
      `- Reproduction: ${evidence.reproduction.command}`,
      ...evidence.tests.map((test) => `- Test: ${test.command} -> ${test.status}`),
      `- Crucible: ${evidence.crucible.verdict}`,
      "",
      "## Provenance",
      `Candidate: ${candidate.issue.url}`,
      "",
      "## Not verified",
      ...(evidence.not_verified?.tests_skipped || []).map((item) => `- Skipped test scope: ${item}`),
      ...(evidence.not_verified?.assumptions || []).map((item) => `- Assumption: ${item}`),
      "Generated by Project Telos OSS Proof Showcase. Public submission remains operator-gated."
    ].join("\n")
  };
}